spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/monitoring-actuator
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://127.0.0.1:4200
        allowed-methods: GET
      base-path: /actuator
      exposure:
        include: "health,httptrace"

  endpoint:
    health:
      show-details: "ALWAYS"
queue:
  name: httprequest

server:
  port: 8081