spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/actuator_database
    username: root
    password: tiro@123

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: "ALWAYS"