spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,httptrace"

  endpoint:
    health:
      show-details: "ALWAYS"